spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    # 开发禁用缓存
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/shiro?characterEncoding=UTF-8&useSSL=true
    username: root
    password: cqits123
    # 可省略驱动配置, sprin-boot 会由url检测出驱动类型
    # driver-class-name: com.mysql.jdbc.Driver
    druid:
      # 连接池配置
      initial-size: 1
      min-idle: 1
      max-active: 10
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      validation-query: SELECT 'x'
      filter:
        stat:
          ## 是否开启慢查询统计
          log-slow-sql: true
          ## 慢查询的定义
          slow-sql-millis: 2000
          ## 是否开启合并参数化 SQL
          merge-sql: true
      # 监控配置
      web-stat-filter:
        url-pattern: /*     
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        
      # StatViewServlet配置
      stat-view-servlet:
        login-username: admin
        login-password: 123
        allow: 127.0.0.1
        reset-enable: false
mybatis:
  mapperLocations: classpath:com/boot/mapper/*.xml
  typeAliasesPackage: com.boot.domain
# spring-boot默认打印输出info级别以上的，可在此处修改输出级别
logging:
  level:
    root: info
server:
  port: 9090